name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - notebook
  - pandas=1.5.2
  - pip=20.3.3
  - pandas-profiling
  - pyarrow=2.0
  - pip:
      - wandb==0.13.5
