wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1670574777.67929
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.13.5
      8:
      - 5
input_artifact:
  desc: null
  value: sample.csv:latest
max_nights:
  desc: null
  value: 365
max_price:
  desc: null
  value: 350.0
min_nights:
  desc: null
  value: 1
min_price:
  desc: null
  value: 10.0
output_artifact:
  desc: null
  value: clean_sample.csv
output_description:
  desc: null
  value: CSV file after cleaning steps
output_type:
  desc: null
  value: clean_sample
